import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';

const fonts = Ubuntu({
  weight: ['500', '700'],
  subsets: ['latin'],
  variable: '--ubuntu',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={fonts.variable}>
      <body>{children}</body>
    </html>
  );
}